### ISSUE TITLE
Problem with downloading version 2.0.2 via composer

### ISSUE THREAD

**Issue by ngrzechnikCepd** [TrustMateSA/MagentoPlugin#13]
Hi, I have a problem downloading version 2.0.2 using composer
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/108653138/192869620-831ccdcd-ba6a-4e3e-8490-44bcabc6ebe3.png">

**Comment by MLupinski** [comment]
Hello, there is an issue with the version of release. Please try download module with 2.0.1 version.
