### ISSUE TITLE
syntax error, unexpected '|', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by adamwaclawczyk** [TrustMateSA/MagentoPlugin#32]
https://github.com/TrustMateSA/MagentoPlugin/blame/b44b895f9b1a4b8719a1abc5b78d468745f9c64a/Block/Product/View/ListView.php#L74

This breaks support for projects with PHP < 8

**Comment by zergu** [comment]
Fixed in [3.0.6](https://github.com/TrustMateSA/MagentoPlugin/releases/tag/3.0.6)
